theme: jekyll-theme-minimal
logo: https://github.com/sagnikbm/homepage/blob/gh-pages/SagnikBasumallikLANE-6.jpg?raw=true
title: साग्निक बसुमल्लिक
# title: sagnik basumallik
description: इंजीनियरिंग वैज्ञानिक, <a href="https://resilientpowergrid.ai">स्मार्ट ग्रिड रेसिलिएन्सी एंड एनालिटिक्स लैब </a>,  वेस्ट वर्जिनिया यूनिवर्सिटी, लेन डिपार्टमेंट ऑफ़ कंप्यूटर साइंस एंड इलेक्ट्रिकल इंजीनियरिंग  <br><br>sagnik.basumallik[@]mail.wvu.edu<br><br><a href="https://scholar.google.com/citations?user=pzYJwgEAAAAJ&hl=en">गूगल स्कॉलर</a>
github:
  is_project_page: false
# description: engineering scientist, <a href="https://resilientpowergrid.ai">smart grid resiliency and analytics lab</a>,  west virginia university, lane department of computer science and electrical engineering <br><br>sagnik.basumallik[@]mail.wvu.edu<br><br><a href="https://scholar.google.com/citations?user=pzYJwgEAAAAJ&hl=en">google scholar</a>
