theme: jekyll-theme-minimal
logo: https://github.com/sagnikbm/homepage/blob/gh-pages/Basumallik_Sagnik_h.jpg?raw=true
title: साग्निक बसुमल्लिक
description: research scientist, <a href="https://resilientpowergrid.ai">smart grid resiliency and analytics lab</a>,  west virginia university, lane department of computer science and electrical engineering <br><br>ph.d., syracuse university, ny, 2021 <br><br><a href="https://scholar.google.com/citations?user=pzYJwgEAAAAJ&hl=en">google scholar</a>
github:
  is_project_page: false
