theme: jekyll-theme-minimal
logo: https://github.com/sagnikbm/homepage/blob/gh-pages/Basumallik_Sagnik_h.jpg?raw=true
title: sagnik basumallik
github:
  is_project_page: false
description: research scientist, <a href="https://resilientpowergrid.ai">smart grid resiliency and analytics lab</a>,  west virginia university, lane department of computer science and electrical engineering 
<br><br><a href="https://scholar.google.com/citations?user=pzYJwgEAAAAJ&hl=en">google scholar</a>
<br><br> assistant professor (teaching) - university of colorado, boulder, 2021 - 2022
<br><br> ph.d fellow, syracuse university, new york, 2015 - 2021
<br><br> b.tech, west bengal university, india, 2010 - 2014

