theme: jekyll-theme-minimal
logo: https://github.com/sagnikbm/homepage/blob/gh-pages/Basumallik_Sagnik_h.jpg?raw=true
title: sagnik basumallik
description: research scientist, west virginia university, lane department of computer science and electrical engineering
permalink: https://resilientpowergrid.ai/index.html
